version: '3'

services:
  io.swagger:
    container_name: home-web
    image: josemottalopes/home-web
    build:
      context: .
      dockerfile: Lirc/lirc-web.Dockerfile
    ports:
    - "5010"
    network_mode: bridge
    privileged: true
    restart: always
    volumes:
    - /var/run/lirc:/var/run/lirc
    environment:
      - ASPNETCORE_ENVIRONMENT=Release

  home.ui:
    container_name: home-ui
    image: josemottalopes/home-ui
    build:
      context: .
      dockerfile: src/Home.UI/pi.Dockerfile
    ports:
    - "80"
    network_mode: bridge
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
 
  ssl.proxy:
    container_name: ssl-proxy
    image: josemottalopes/nginx-proxy
    build:
      context: .
      dockerfile: proxy.Dockerfile
    ports:
    - "443"
    network_mode: bridge